version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/movieflix
      - DB_USERNAME= ${DB_USERNAME}
      - DB_PASSWORD= ${DB_PASSWORD}
      - MOVIEFLIX_SECURITY_SECRET=${MOVIEFLIX_SECURITY_SECRET}
  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=movieflix
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}